#!/usr/bin/env bun

import { type BuildConfig, type BunPlugin } from "bun";
import fsp from "fs/promises";
import { join, parse } from "path";
import process from "process";
import { compile, preprocess } from "svelte/compiler";
import { version } from "../../package.json" assert { type: "json" };
import svelteConfig from "./svelte.config.js";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit https://github.com/istefox/obsidian-mcp-connector
*/
`;

// Parse command line arguments
const args = process.argv.slice(2);
const isWatch = args.includes("--watch");
const isProd = args.includes("--prod");

// Stub `onnxruntime-node` and `sharp` with empty modules. Transformers.js
// has eager `require()` paths for these node-only optional dependencies
// (no try/catch fallback), so even marking them `external` leaves a
// runtime `require("onnxruntime-node")` that Electron's renderer can't
// resolve — the plugin then fails to load with "Cannot find module
// 'onnxruntime-node'". Replacing them with an empty module makes the
// require return `{}`; Transformers.js's runtime detection then picks
// the WASM/onnxruntime-web backend, which is what we actually want in
// the Electron environment.
const stubEmptyModulesPlugin: BunPlugin = {
  name: "stub-empty-modules",
  setup(build) {
    build.onResolve({ filter: /^(onnxruntime-node|sharp)$/ }, (args) => ({
      path: args.path,
      namespace: "stub-empty",
    }));
    build.onLoad(
      { filter: /.*/, namespace: "stub-empty" },
      () => ({
        contents: "module.exports = {};",
        loader: "js",
      }),
    );
  },
};

// Svelte plugin implementation
const sveltePlugin: BunPlugin = {
	name: "svelte",
	setup(build) {
		build.onLoad({ filter: /\.svelte$/ }, async ({ path }) => {
			try {
        const parsed = parse(path);
				const source = await Bun.file(path).text();
        const preprocessed = await preprocess(source, svelteConfig.preprocess, {
          filename: parsed.base,
        });
        const result = compile(preprocessed.code, {
          filename: parsed.base,
					generate: "client",
					css: "injected",
					dev: isProd,
				});

				return {
					loader: "js",
					contents: result.js.code,
				};
			} catch (error) {
				const message =
					error instanceof Error ? error.message : String(error);
				throw new Error(`Error compiling Svelte component: ${message}`);
			}
		});
	},
};

const config: BuildConfig = {
  entrypoints: ["./src/main.ts"],
  outdir: "../..",
  minify: isProd,
  plugins: [stubEmptyModulesPlugin, sveltePlugin],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Note: `onnxruntime-node` and `sharp` are NOT in this `external`
    // list. They're handled by the `stubEmptyModulesPlugin` above
    // which replaces them with empty modules at bundle time —
    // marking them `external` would leave a literal
    // `require("onnxruntime-node")` in main.js that Electron cannot
    // resolve (observed: "Cannot find module 'onnxruntime-node'" at
    // plugin load).
  ],
  target: "node",
  format: "cjs",
  conditions: ["browser", isProd ? "production" : "development"],
  sourcemap: isProd ? "none" : "inline",
  define: {
    "process.env.NODE_ENV": JSON.stringify(
      isProd ? "production" : "development",
    ),
    "import.meta.filename": JSON.stringify("mcp-tools-for-obsidian.ts"),
    // These environment variables are critical for the MCP server download functionality.
    // In CI the release workflow injects the correct values (see .github/workflows/release.yml);
    // the fallback targets the active fork repo so local builds keep working.
    // Hardcoding upstream here silently overrode the CI env vars and shipped 404-ing
    // download URLs in releases — see issue #3.
    "process.env.GITHUB_DOWNLOAD_URL": JSON.stringify(
      process.env.GITHUB_DOWNLOAD_URL ??
        `https://github.com/istefox/obsidian-mcp-connector/releases/download/${version}`,
    ),
    "process.env.GITHUB_REF_NAME": JSON.stringify(
      process.env.GITHUB_REF_NAME ?? version,
    ),
  },
  naming: {
    entry: "main.js", // Match original output name
  },
  // Add banner to output
  banner,
};

async function build() {
	try {
		const result = await Bun.build(config);

		if (!result.success) {
			console.error("Build failed");
			for (const message of result.logs) {
				console.error(message);
			}
			process.exit(1);
		}

		console.warn("Build successful");
	} catch (error) {
		console.error("Build failed:", error);
		process.exit(1);
	}
}

async function watch() {
	const watcher = fsp.watch(join(import.meta.dir, "src"), {
		recursive: true,
	});
	console.warn("Watching for changes...");
	for await (const event of watcher) {
		console.warn(`Detected ${event.eventType} in ${event.filename}`);
		await build();
	}
}

async function main() {
	if (isWatch) {
		await build();
		return watch();
	} else {
		return build();
	}
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
